version: "3"

services:
  webapp:
    container_name: counter_webapp
    build:
      context: .
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - app_net
    links:
      - db_postgres
    depends_on:
      - db_postgres

  db_postgres:
    container_name: db_postgres
    build:
      context: ./docker/postgres
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - app_net

networks:
  app_net:
