version: "3"

services:
  webapp:
    container_name: counter_webapp
    build:
      context: .
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - app_net
    links:
      - redis
      - db_postgres
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
    depends_on:
      - redis
      - db_postgres

  db_postgres:
    container_name: db_postgres
    build:
      context: ./docker/postgres
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - app_net

  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - app_net

networks:
  app_net:
